// Generated by https://pagedraw.io/pages/12222
import React from 'react';
import Singlebutton from './singlebutton';
import './inheritedbutton.css';


export default class Inheritedbutton extends React.Component {
  render() {
    return (
      <div className="inheritedbutton-inheritedbutton-7">
          <div className="inheritedbutton-0">
              <div className="inheritedbutton-singlebutton-1">
                  <Singlebutton fixedText={this.props.buttonObject.fixedText} handleClick={this.props.handleClick} action={this.props.buttonObject.action} subAction={this.props.buttonObject.subAction} /> 
              </div>
          </div>
      </div>
    );
  }
};
