// Generated by https://pagedraw.io/pages/12222
import React from 'react';
import './inputtextbox.css';


export default class Inputtextbox extends React.Component {
  render() {
    return (
      <div className="inputtextbox-inputtextbox-7">
          <div className="inputtextbox-0">
              <input type="text" placeholder="Placeholder" onChange={(text) => this.props.onChangeText(text, this.props.action)} className="inputtextbox-text_input-1" /> 
          </div>
      </div>
    );
  }
};
