// Generated by https://pagedraw.io/pages/12222
import React from 'react';
import Singlebutton from './singlebutton';
import Textoutput from './textoutput';
import Inputtextbox from './inputtextbox';
import Combinedcomponent from './combinedcomponent';
import './mainpagewithcombined.css';


export default class Mainpagewithcombined extends React.Component {
  render() {
    return (
      <div className="mainpagewithcombined-mainpagewithcombined-4">
          <div className="mainpagewithcombined-0">
              <div className="mainpagewithcombined-0-0">
                  <div className="mainpagewithcombined-0-0-0">
                      <div className="mainpagewithcombined-singlebutton_instance-0">
                          <Singlebutton fixedText={""} handleClick={this.props.handleClick} action={"BUTTON_CLICK"} subAction={"Left"} /> 
                      </div>
                  </div>
              </div>
              <div className="mainpagewithcombined-0-1">
                  <div className="mainpagewithcombined-0-1-0">
                      <div className="mainpagewithcombined-textoutput_instance-6">
                          <Textoutput fixedText={this.props.fixedText} /> 
                      </div>
                  </div>
                  <div className="mainpagewithcombined-0-1-1">
                      <div className="mainpagewithcombined-inputtextbox_instance-2">
                          <Inputtextbox onChangeText={this.props.onChangeText} action={"textInput"} /> 
                      </div>
                  </div>
              </div>
              <div className="mainpagewithcombined-0-2">
                  <div className="mainpagewithcombined-0-2-0">
                      <div className="mainpagewithcombined-singlebutton_instance-6">
                          <Singlebutton fixedText={""} handleClick={this.props.handleClick} action={"BUTTON_CLICK"} subAction={"Right"} /> 
                      </div>
                  </div>
              </div>
          </div>
          <div className="mainpagewithcombined-1">
              <div className="mainpagewithcombined-combinedcomponent_instance-5">
                  <Combinedcomponent CombinedObject={this.props.CombinedObject} handleClick={this.props.handleClick} onChangeText={this.props.onChangeText} /> 
              </div>
          </div>
          <div className="mainpagewithcombined-2" /> 
      </div>
    );
  }
};
