// Generated by https://pagedraw.io/pages/12222
import React from 'react';
import Singlebutton from './singlebutton';
import Textoutput from './textoutput';
import Inputtextbox from './inputtextbox';
import './mainpage.css';


export default class Mainpage extends React.Component {
  render() {
    return (
      <div className="mainpage-mainpage-4">
          <div className="mainpage-0">
              <div className="mainpage-0-0">
                  <div className="mainpage-0-0-0">
                      <div className="mainpage-singlebutton_instance-8">
                          <Singlebutton fixedText={""} handleClick={this.props.handleClick} action={"BUTTON_CLICK"} subAction={"Left"} /> 
                      </div>
                  </div>
              </div>
              <div className="mainpage-0-1">
                  <div className="mainpage-0-1-0">
                      <div className="mainpage-textoutput_instance-3">
                          <Textoutput fixedText={this.props.fixedText} /> 
                      </div>
                  </div>
                  <div className="mainpage-0-1-1">
                      <div className="mainpage-inputtextbox_instance-7">
                          <Inputtextbox onChangeText={this.props.onChangeText} action={"textInput"} /> 
                      </div>
                  </div>
              </div>
              <div className="mainpage-0-2">
                  <div className="mainpage-0-2-0">
                      <div className="mainpage-singlebutton_instance-83">
                          <Singlebutton fixedText={""} handleClick={this.props.handleClick} action={"BUTTON_CLICK"} subAction={"Right"} /> 
                      </div>
                  </div>
              </div>
          </div>
          <div className="mainpage-1" /> 
      </div>
    );
  }
};
