// Generated by https://pagedraw.io/pages/12222
import React from 'react';
import './singlebutton.css';


export default class Singlebutton extends React.Component {
  render() {
    return (
      <div onClick={this.props.handleClick.bind(this, this.props)} className="singlebutton-singlebutton-5">
          <div className="singlebutton-0">
              <div className="singlebutton-buttonbox-5">
                  <div className="singlebutton-0-0-0">
                      <div className="singlebutton-buttontext-9">
                          SingleButton
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
