// Generated by https://pagedraw.io/pages/12222
import React from 'react';
import './textoutput.css';


export default class Textoutput extends React.Component {
  render() {
    return (
      <div className="textoutput-textoutput-4">
          <div className="textoutput-0">
              <div className="textoutput-textoutputshown-2">
                  <div className="textoutput-0-0-0">
                      <div className="textoutput-type_something_-2">
                          { this.props.fixedText }
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
